spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paring_user
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # For dev; use 'none' in prod
server:
  port: 8081  # Port khusus untuk service ini