version: "3.9"

services:
  # Auth service (dummy example)
  auth-service:
    build: ./services/auth-service
    ports:
      - "3000:3000"

  order-service:
    build: ./services/order-service
    ports:
      - "3001:3001"

  # Redis (untuk pub/sub event)
  redis:
    image: redis:7
    ports:
      - "6379:6379"

  # Kong (API Gateway)
  kong:
    image: kong:3.4
    restart: always
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
    ports:
      - "8000:8000"  # proxy
      - "8001:8001"  # admin API
    volumes:
      - ./kong:/kong/declarative
    depends_on:
      - auth-service
